"""Initial migration

Revision ID: 081a3891dfe8
Revises: 
Create Date: 2026-02-04 19:59:46.903896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081a3891dfe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('theme_preference', sa.Enum('light', 'dark'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('client_id_encrypted', sa.Text(), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('scanner_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('stock_selection', sa.JSON(), nullable=True),
    sa.Column('strike_range', sa.Integer(), nullable=True),
    sa.Column('price_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scanner_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scanner_configs_user_id'), ['user_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scanner_config_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('live', 'backtest'), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('option_type', sa.Enum('CE', 'PE'), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_change_percent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scanner_config_id'], ['scanner_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_user_id'))
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_mode'))
        batch_op.drop_index(batch_op.f('ix_signals_detected_at'))

    op.drop_table('signals')
    with op.batch_alter_table('scanner_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scanner_configs_user_id'))

    op.drop_table('scanner_configs')
    op.drop_table('api_credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
