"""add api token cache and mpin

Revision ID: 0c7b2f2f4521
Revises: e5d3035c0ea8
Create Date: 2026-02-06 21:14:56.393373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7b2f2f4521'
down_revision = 'e5d3035c0ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_mpin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auth_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feed_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('feed_token_encrypted')
        batch_op.drop_column('refresh_token_encrypted')
        batch_op.drop_column('auth_token_encrypted')
        batch_op.drop_column('use_mpin')

    # ### end Alembic commands ###
