"""add api key fields

Revision ID: e5d3035c0ea8
Revises: bc06aa653e22
Create Date: 2026-02-06 20:14:16.324932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5d3035c0ea8'
down_revision = 'bc06aa653e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_market_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('api_key_historical_encrypted', sa.Text(), nullable=True))
        batch_op.alter_column('api_key_encrypted',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.alter_column('api_key_encrypted',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('api_key_historical_encrypted')
        batch_op.drop_column('api_key_market_encrypted')

    # ### end Alembic commands ###
